"""empty message

Revision ID: 8f67c60396fc
Revises: 4fc2efd2e0e9
Create Date: 2022-10-19 14:34:07.880051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f67c60396fc'
down_revision = '4fc2efd2e0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comuna', type_='foreignkey')
    op.drop_column('comuna', 'id_region')
    op.drop_constraint(None, 'direcciones', type_='foreignkey')
    op.drop_column('direcciones', 'id_region')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direcciones', sa.Column('id_region', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'direcciones', 'comuna', ['id_region'], ['id_region'])
    op.add_column('comuna', sa.Column('id_region', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'comuna', 'provincia', ['id_region'], ['id_region'])
    # ### end Alembic commands ###
